name:                Markov
version:             0.1.0.0
github:              "cspollard/Markov"
license:             BSD3
author:              "Chris Pollard"
maintainer:          "cspollard@gmail.com"
copyright:           "2022 Chris Pollard"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/cspollard/Markov#readme>

dependencies:
- base >= 4.7 && < 5
- primitive
- pipes
- linear
- mwc-random
- mwc-probability

library:
  source-dirs: src
